const prompts = [
 const prompts = [
"[insert name] confesses something they should’ve said a long time ago and [insert name] isn’t sure how to respond.",
"[insert name] finds an old love letter from [insert name] that was never sent.",
"[insert name] is supposed to be focusing on the game, but keeps watching [insert name] laugh with someone else.",
"[insert name] skips practice, and [insert name] finds them alone in the locker room, crying.",
"[insert name] comforts [insert name] after they get rejected by their crush.",
"[insert name] brings [insert name] a homemade lunch after they find out their home situation.",
"after a long day, [insert name] comes home to see [insert name] cooking a warm meal.",
"[insert name] finds [insert name] sleeping in the library.",
"during a field trip, [insert name] gives [insert name] their jacket.",
"[insert name] asks [insert name] if they need study help after they see their last exam result.",
"[insert name] accidentally likes their crush’s old post.",
"[insert name] offers [insert name] a ride home after their shift together.",
"[insert name] wears a dress in [insert name]’s favorite color.",
"[insert name] is nervous to meet [insert name]’s parents for the first time.",
"[insert name] discovers a separate group chat without them.",
"[insert name] starts a fight with someone trying to flirt with [insert name].",
"[insert name] is a gaming streamer, and [insert name] secretly watches their stream.",
"[insert name] and [insert name] have a pillow fight.",
"[insert name] takes [insert name] to a work event.",
"[insert name] helps [insert name] set up a YouTube channel.",
"[insert name] brags about [insert name] to their friends.",
"[insert name] invites [insert name] to a party.",
"[insert name] takes [insert name] to a new cafe.",
"[insert name] and [insert name] have a cozy night in on a rainy afternoon.",
"[insert name] tries to impress [insert name] with their bad basketball skills.",
"[insert name] and [insert name] hold hands at the movies.",
"[insert name] owes [insert name] money.",
"[insert name] lends [insert name] a helping hand.",
"[insert name] bakes [insert name] a birthday cake.",
"[insert name] is a therapist and [insert name] is comfortable to talk to them.",
"[insert name] sees [insert name] in their wedding dress for the first time.",
"[insert name] and [insert name] have a beach day.",
"[insert name] and [insert name] spend Christmas together.",
"[insert name] and [insert name] prank trick-or-treaters together.",
"[insert name] is nervous to go to a Halloween party, [insert name] reassures them.",
"[insert name] and [insert name] have a heated debate.",
"[insert name] is scared of thunder, [insert name] holds them through it.",
"[insert name] and [insert name] go to the fair.",
"[insert name] catches [insert name] staring at them in class.",
"[insert name] and [insert name] have a late night call.",
  "[insert name] helps [insert name] clean their closet.",
"[insert name] and [insert name] slow dance.",
"[insert name] shows up to [insert name]'s performance, they spot them in the crowd and smile.",
"[insert name] shows up at night to [insert name]'s house saying 'I couldn't sleep.'",
"[insert name] used to wait by [insert name]'s locker, now they walk past it.",
"[insert name] says 'we were just kids.' [insert name] still remembers every second.",
"[insert name] helps [insert name] with their long procrastinated project.",
"[insert name] offers to pay for [insert name]'s lunch.",
"[insert name] offers to walk [insert name] home in the rain.",
"[insert name] teaches [insert name] how to swim.",
"[insert name] casts a love spell, but [insert name] was already in love.",
"[insert name] surprises [insert name] with a cat.",
"[insert name] gives [insert name] their team jacket back without a word.",
"[insert name] trains harder just to impress [insert name], but they don't notice.",
"[insert name] says something they can't take back, and [insert name] doesn't respond.",
"[insert name] sketches [insert name] in their notebook, but someone finds out.",
"[insert name] and [insert name] live together on a farmhouse.",
"[insert name] sneaks into [insert name]'s house to make a pillow fort.",
"[insert name] fixes [insert name]'s tie before prom.",
"[insert name] realizes their love for [insert name] far too late.",
"[insert name] accidentally hurts [insert name].",
"[insert name] and [insert name] meet again after years of not talking.",
"[insert name] finds a letter in their locker, the writing is familiar.",
"[insert name] and [insert name] break up. Years later, they meet at a friend's wedding.",
"[insert name] waits for [insert name] at a restaurant. They don't show up.",
"[insert name] waits at a bus stop with a gift for [insert name] they never got to give.",
"[insert name] watches everyone else leave the party. [insert name] said they'd come.",
"[insert name] and [insert name] grow old together.",
"[insert name] and [insert name] win the lottery, what they choose to spend on is up to you.",
"[insert name] and [insert name] cut each other's hair.",
"[insert name] steals [insert name]'s hoodie.",
"[insert name] buys [insert name] art supplies.",
"[insert name] pretends to be asleep so [insert name] will carry them to bed.",
"[insert name] pulls the blanket over [insert name] without waking them.",
"[insert name] and [insert name] fall asleep on call.",
"[insert name] and [insert name] make a midnight snack together.",
"[insert name] and [insert name] go for a late night drive.",
"[insert name] memorizes [insert name]'s coffee order.",
"[insert name] stands up for [insert name].",
"[insert name] gives [insert name] a promise ring.",
"[insert name] and [insert name] have a beach wedding.",
"[insert name] and [insert name] run away together.",
"[insert name] and [insert name] read together in a tree.",
"[insert name] convinces [insert name] to explore haunted places with them.",
"[insert name] and [insert name] watch the sunset together.",
"[insert name] teaches [insert name] how to surf.",
"walking through a crowded hall, [insert name] accidentally bumps into [insert name], causing their fall.",
"[insert name] and [insert name] get into a huge fight.",
"[insert name] takes pictures of [insert name] with a digital camera in golden hour light.",
"[insert name] and [insert name] meet for the first time at a bar.",
"[insert name] finds out [insert name] is using them for money.",
"[insert name] picks [insert name] flowers.",
"[insert name] sews [insert name] a new dress.",
"[insert name] steals [insert name]'s snacks.",
"[insert name] and [insert name] lose each other during a zombie apocalypse.",
"[insert name] has to leave [insert name] behind.",
"[insert name] is a detective who tries to solve [insert name]'s murder.",
"[insert name] writes a book about [insert name].",
  
];
];

function generatePrompt() {
  const random = prompts[Math.floor(Math.random() * prompts.length)];
  document.getElementById("output").innerText = random;
}
